extends: airbnb-base
installedESLint: true
plugins:
  - import
rules:
  arrow-body-style: 0
  max-len: 0
  semi:
    - error
    - never
  no-console: 0
  no-restricted-syntax: 0
  no-use-before-define: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  no-constant-condition: 0
  func-names: 0
  no-class-assign: 0
  no-extra-boolean-cast: 0
  no-nested-ternary: 0
  eol-last: 0
  radix: 0
  comma-dangle:
    - error
    - functions: ignore
      objects: always-multiline
      arrays: always-multiline